name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.2.0

    - name: Build and Deploy
      run: 
       
        npm install --global surge
        surge token 9e3245c4523779c03a01ac588e5a7f1a

        surge --project ./ 
